---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.app.appName }}
  namespace: default
spec:
  schedule: "1 1 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
              - bash
              - '-c'
              - |
                MODEL_DIR=$(mktemp -d)
                bin/train-prod-model "$MODEL_DIR"
                MODEL_FILE=$(find $MODEL_DIR -name '*.crfmodel')
                echo Done Bulding file $MODEL_FILE !

                az storage blob upload -c models -n $(date +%Y-%m-%d).crfmodel -f $MODEL_FILE --account-name "ingredienttagger" --account-key $INGRED_TAGGER_ACCESS_KEY
                echo Uploaded crfmodel model file

            env:
              - name: ENV
                value: dev
              - name: INGRED_TAGGER_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: vault-ingred-tagger
                    key: access-key
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 1
                  preference:
                    matchExpressions:
                      - key: indexer
                        operator: In
                        values:
                          - 'true'
          tolerations:
            - key: dedicated
              operator: Equal
              value: indexer
              effect: NoSchedule
            image: sifteracr.azurecr.io/{{ .Values.app.appName }}:#{IMAGE_TAG}
            imagePullPolicy: Always
            name: {{ .Values.app.appName }}
            resources: {}
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: imagepullsecretesifter
